#! /bin/bash
eval $(ssh-agent)
ssh-add

function gitStuff {
    echo -e "syncing $(pwd)"
    [ -n "$(git status -s)" ] &&    # if no change, no commit
    read -p "would you like to continue? [Y/n]" &&
    if [[ "$REPLY" =~ [Yy] ]]; then
        git fetch -q && git diff --stat && git pull -q && git add . && git commit -qm "script sync: $(git status -s)" && git push -q
    else
        true    # pass / do nothing
    fi
}

function traverse {
    [ "$#" -ne 1 ] && exit 1
    [ ! -d "$1" ] && exit 2
    local base="$(pwd)"
    cd "$1"
    if [ -d .git ]
    then
        gitStuff
    else
        local branches=($(ls -A))
        for file in "${branches[@]}"; do
            [[ "$file" =~ [Vv]env ]] && continue
            if [ -d "$file" ]; then
                traverse "$file"
            fi
        done
    fi
    cd "$base"
}

whereMyCodeIs=("$PERSONAL" "$MY_DOTFILES" "$CODESPACE")

for dir in "${whereMyCodeIs[@]}"; do traverse "$dir"; done && exit 0
