#! /bin/bash
eval $(ssh-agent)
ssh-add
cd $PERSONAL
git pull -q && git diff --stat && git add . && git commit -qm "routine sync via script" && git push -q
cd $OLDPWD
cd $MY_DOTFILES
git pull -q && git diff --stat && git add . && git commit -qm "routine sync via script" && git push -q
cd $OLDPWD
cd $SCRIPTSPACE
git pull -q && git diff --stat && git add . && git commit -qm "routine sync via script" && git push -q
cd $OLDPWD
cd "$CODESPACE/Advent-of-Code"
git pull -q && git diff --stat && git add . && git commit -qm "routine sync via script" && git push -q
cd $OLDPWD
